### ISSUE TITLE
Translation selectors lost

### ISSUE THREAD

**Issue by jemelyah** [Gottwik/Enduro#102]
After deploying the enduro app with PM2 lost the translation tabs - translations are working, but I can't manipulate them in prod.
<img width="386" alt="2017-08-03 13 05 04" src="https://user-images.githubusercontent.com/7820065/28916911-72e9aa6e-784c-11e7-8ab2-d0fe20d6c753.png">

**Comment by Gottwik** [comment]
that's weird. Does it throw any errors? How do you start it with pm2?

Are the culture pages rendered(you can check at `localhost:5000/de`)? Is it just that the culture tabs are not shown in the admin?

**Comment by jemelyah** [comment]
One of logs:
Error: ENOENT: no such file or directory, stat '/var/www/rehab/production/source/_generated/config/babel/index.html'
    at Error (native)
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

Second one appearing over and over:
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:322:13
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
    at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:906:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:165:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:2128:10)
    at FSReqWrap.oncomplete (fs.js:123:15)

Cultures in the front are rendered flawless, it's only the admin lang tabs that are missing.
PM2:
I deploy it via pm2 ecosystem with such settings:
...// Production application
    {
      name      : 'rehab',
      script    : 'enduro',
      args: 'start',
      cwd: '/var/www/rehab/production/current',
      instances : 0,
      exec_mode : "cluster",
      env: {
        COMMON_VARIABLE: 'true',
        PORT: '5169'
      },
      env_production : {
        NODE_ENV: 'production'
      }
    }
  ], ...

After deploy it runs `npm i`

**Comment by jemelyah** [comment]
Even if I launch enduro on the prod with `enduro start`, the cultures don't appear.

**Comment by Gottwik** [comment]
Could you try inserting the cultures again? `enduro culture add en de es fr`. We changed how cultures are stored recently, could it be that you updated enduro?

How does your enduro.json look? The cultures should be there.

**Comment by jemelyah** [comment]
{
	"project_name": "Rehab",
	"project_slug": "rehab",
	"s3": {
		"bucket": "enduro.sethere",
		"region": "eu-west-1"
	},
	"juicebox_enabled": false
}

**Comment by Gottwik** [comment]
Did re-adding the cultures get it fixed?

**Comment by jemelyah** [comment]
Awesome! It did!

**Comment by Gottwik** [comment]
sorry that you had this issue. don't forget to set a fixed version of enduro as dependency when you have your project ready. We try to do non-breaking changes, but sometimes this still happens I guess.
