### ISSUE TITLE
Deploying to Heroku from scratch

### ISSUE THREAD

**Issue by karneaud** [Gottwik/Enduro#104]
Based on your documentation if you created your project using `enduro create app` you should be good to go.

What if you didn't use `enduro create app` .....what is needed to deploy to heroku?

**Comment by Gottwik** [comment]
Most of the hassle, such as using the port your heroku app is built into enduro in a general way, so 

All you really need is to start enduro in npm's package.json:

```
"scripts": {
    "postinstall": "node_modules/bower/bin/bower install",
    "start": "node_modules/.bin/enduro start"
},
```

btw, you are free to use yarn or whatever, just include it as the postinstall script.

Does this answer your question?

**Comment by karneaud** [comment]
Yes. Will try this out
