### ISSUE TITLE
Access content files in client javascript

### ISSUE THREAD

**Issue by karneaud** [Gottwik/Enduro#107]
I have a situation where I need to access variables from `cms/content_files` in my client side javascript.

Is there any way to export/ access it on client side javascript for consumption maintaining editablity?

**Comment by Gottwik** [comment]
There is a handlebars helper for this:

```html
<script>
	const list_of_people_i_need_in_javascript = {{{js_cms people}}}
</script>
```

This gets handlebars context as you would see if you did `{{log people}}`.

Example context file:
```js
{
    people: [
        {
            name: 'martin'
        },
        {
            name: 'tim'
        },
    ]
}
```

Does this help you?
