### ISSUE TITLE
Routing with Main layout page

### ISSUE THREAD

**Issue by dannydel** [Gottwik/Enduro#108]
Hello!

My buddy and I have been working on a project using Enduro.js and it's been pretty awesome to work with so far!

We have finally gotten to a point where we need multiple pages for our website. I know there must be a way to render and route pages with a main layout page. I am a bit lost with this.

I checked out your dynamic serving post but I didn't seem to gather much different of info than what I was trying out. 

I have tried something like this:
within my app.js

```
local_app.prototype.init = function (app) {
	app.set('view options', {layout: 'main.hbs'});

	app.get('/', function(req,res){
		res.send('index');
	})

	app.get('/guys_team', function(req,res){
		res.send('/guys_team/index');
	})
```

and within my index.hbs after I have made my navigation
```
   <main class="mdl-layout__content">
        {{{body}}}
      </main>
```

It'd be really appreciated to have a some guidance here!

Cheers!

**Comment by Gottwik** [comment]
Hey @dannydel, do you actually need dynamic pages? These are rendered each time a user requests it.

My guess is you just want to add a static page. To, let's say, add a **contact** page, just add `/pages/contact.hbs` and `/cms/contact.js` files.

Does this help? Do you have any other questions?

**Comment by dannydel** [comment]
Actually, I think I understand what I need to do for what I want. Instead of thinking of a main layout page, I can just make partials to give the feel of a layout page all while using statically rendered hbs pages. Like:

index.hbs
```
<html>
<body>
{{> _nav}}
{{> _index_partial}}
{{> _footer}}
</body>
</html>
```

and the same for each consecutive static pages I make such as `/pages/contact.hbs`. 

Thank you for the help, @Gottwik ! I really like enduro so far, and I will probably be using it in other projects!

**Comment by Gottwik** [comment]
Exactly, you figured it out. These are called components 

Read more here: https://www.endurojs.com/docs/templates#components

Components get context from the page's context files(`/cms/contact.js`), but you can also put context anywhere in the `/cms/global` folder and this context will be accessible by all components by `global.<your_object>`.

So, you can create `/cms/global/main_navigation.js` and put:

```js
{
    main_navigation_items: [
        {
            label: 'about us'
        },
        {
            label: 'products'
        },
        {
            label: 'contact'
        },
    ]
}
```

and then access it with your _nav component you placed in `/components/_nav.hbs` like this:

```html
<ul>
    {{#each global.main_navigation_items}}
        <li>{{label}}</li>
    {{/each}}
</ul>
```

**Comment by dannydel** [comment]
Already ahead of you! Thanks again!
