### ISSUE TITLE
bower?

### ISSUE THREAD

**Issue by Gusbenz** [Gottwik/Enduro#109]
Great project!

Just came across it today and it looks great for my needs.

I was wondering were the bower stuff comes into play and why it rolls with it? I've taken a cursory glance, so forgive me if it's obvious. Bower seems to be headed to deprecation and that is why I ask. 

Thanks!

**Comment by israelroldan** [comment]
The project scaffold contains .bowerrc and bower.json in case you choose to use it but it is certainly not a must, you can develop your whole site without ever using bower.

Personally, I sometimes use bower with enduro for front end dependencies which I don't want to serve from node_modules, but if you use Webpack or other bundle tools then it doesn't really make a difference.

**Comment by Gottwik** [comment]
Thank you for pointing the bower out. There is a plan to integrate yarn, especially to enduro theme manager and enduro admin.

Apart from that, as @israelroldan said, there is no real coupling with bower at the moment, and you are free to use whatever to get your frontend or backend dependencies.

Let us know if you have any more thoughts 😄 .

**Comment by Gusbenz** [comment]
Thanks, guys. Closing the issues as my question has been answered.
