### ISSUE TITLE
[Question] Access to contents via api ?

### ISSUE THREAD

**Issue by giovanniRodighiero** [Gottwik/Enduro#117]
Hi I'm playing a bit with Enduro and I'd like to serve my contents through some REST API.

Reading the docs I got how to implement my endpoints, now I am wondering what is the best way to access to the actual contents from the cms folder. Are there some apis in the `enduro` object? Or should I just simply open the file I want with `fs` or a similar module ?

Thanks.

**Comment by giovanniRodighiero** [comment]
Ok I figured it out, [https://www.endurojs.com/docs/linker](Docs).

**Comment by Gottwik** [comment]
good job! The best practice is to use `enduro.api.flat.load(<path content file>)`

good luck with the project, feel free to let us know if you have more questions.
