### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by serbol** [Gottwik/Enduro#121]
How to deploy on server with nodejs installed? Access to admin is required.

I just created a project, then launched enduro start and I can't access the page.
Terminal output:
[20:16:58 | +    2.44] Production server started at port 5000
[20:16:58 | +    0.09] Render started
[20:16:58 | +    0.01] js compiling not enabled, add babel options to enduro.json to enable
[20:16:58 | +       0] Sass compiling started
[20:16:58 | +    0.14] Sass compiling finished

**Comment by Gottwik** [comment]
Can you share more details? If you have a server(your own dedicated one) with node.js, just running `enduro start` will do the job. Beware it will serve everything on port 5000. If it's your server you might try to serve it on port 80 (`sudo enduro start -p=80`).

**Comment by serbol** [comment]
I got this problem now

<img width="1409" alt="screen shot 2017-09-07 at 9 19 48 pm" src="https://user-images.githubusercontent.com/7009754/30176120-5d303530-9412-11e7-9965-5f7e7279508b.png">

**Comment by serbol** [comment]
And page will not work permanently, only when enduro start is working.
