### ISSUE TITLE
duplicate page feature

### ISSUE THREAD

**Issue by serbol** [Gottwik/Enduro#124]
Is it possible to duplicate already created page in admin?
For example, I want to use one page as template (for example, something like post page) that will have same structure as all this type pages, but different content.
If it is not possible to do, than will this feature be implemented later?

**Comment by CosmoMyzrailGorynych** [comment]
It is possible by using [generators](https://www.endurojs.com/docs/generators).

My [Enblog theme](https://github.com/CosmoMyzrailGorynych/enblog_theme) uses generators to create blog posts. You can also find a much simpler example in [samples repository](https://github.com/Gottwik/enduro_samples/tree/master/generators).

Basically, when using generators, you crate a default content file in `cms/generators` folder and a corresponding handlebars template in `pages/generators`. Then you can create new pages from admin UI, in page tree.

**Comment by serbol** [comment]
Thanks!
