### ISSUE TITLE
Theme instalation failed / not finished (without errors)

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#128]
same problem on: **enblog and Mirror**. Maybe I missing some step from the docs. 

Get this:
![image](https://user-images.githubusercontent.com/16711871/30248904-bc3b0000-9638-11e7-9dd2-2749cef4ac97.png)

Create only folder with this files (missing a lot of files):
![image](https://user-images.githubusercontent.com/16711871/30248925-3c0e864e-9639-11e7-9e8a-9a13fdd91e1f.png)

* on windows
* [hello-world](https://www.endurojs.com/docs/hello-world) installation works fine.

**Comment by Gottwik** [comment]
I am pretty sure this is windows related. I will try to fix it asap, ok?

**Comment by Ezra-Siton-UIX** [comment]
OK :) I have windows 7 64bit
One problem i recognize. If i click 3 time enter (project name. login and password its work = i see a lot of files under "www" with this errors):
![image](https://user-images.githubusercontent.com/16711871/30309595-c812ba8c-9794-11e7-81bc-fe52f450cdbd.png)

**Comment by CosmoMyzrailGorynych** [comment]
I can reproduce it on **Windows 8.1**.

There **is** a `bower.json` file in a project directory if you skip 'getting info' steps.

**Comment by Ezra-Siton-UIX** [comment]
Hi. Any new idea how to solve this issue?

**Comment by Ezra-Siton-UIX** [comment]
Update - works fine 1.4.41
**System**: `Windows` | **version**: `enduro 1.4.41`

![image](https://user-images.githubusercontent.com/16711871/32531126-cb617736-c44a-11e7-9cd8-7c22f8e79add.png)

Files folder look like this:
![image](https://user-images.githubusercontent.com/16711871/32531176-0811d220-c44b-11e7-8c78-b62482768216.png)

I find Scss Error (But this not related to this topic - i create another issue):
![image](https://user-images.githubusercontent.com/16711871/32531281-95c784d4-c44b-11e7-8ecf-d06a342b3b2b.png)
