### ISSUE TITLE
How to setup IP & Port configuration?

### ISSUE THREAD

**Issue by chriseaton** [Gottwik/Enduro#13]
Where can you setup the IP binding and port configuration for enduro?

**Comment by Gottwik** [comment]
Hey Chris, enduro will run on port 5000 by default and you can change it by setting environment variable `PORT`. I am blurry on the IP binding, As far as I know it allows any ip address to serve the project. If you provide an use case for this I am happy to add the ip address feature.

**Comment by chriseaton** [comment]
I tried again and it seemed to work, it just confused me because even w/ PORT = 8080, when you run "enduro start" it gives the following output (doesn't mention port 8080 at all).

```
[22:18:34 |    +2.29] Production server started at port 5000
Juicebox is not set up                                      
[22:18:34 |    +0.14] Render started
[22:18:34 |    +0.02] Sass compiling started
[22:18:34 |     +0.2] Sass compiling finished
```

**Comment by Gottwik** [comment]
There are 3 ways to change the default(5000) production port:

- environment variable: `PORT=5001 enduro start`
- cli flag: `enduro start --port=5001`
- enduro configuration(enduro.json) by adding `port: 5001` line

**Comment by zilimojo** [comment]
Is it possible to change both the servers default 3000 port and the admin console 5000 port, when starting with `enduro dev` ?

**Comment by Gottwik** [comment]
@zilimojo , the `enduro dev --port=5001` will work fine, however there is currently no option to set the the 3000 port. Would you like this feature?

**Comment by zilimojo** [comment]
This would be a nice feature, for example to run enduro in development mode on shared server, where not all ports are available.

**Comment by Gottwik** [comment]
@zilimojo I'll try to add that, but in the meantime know that if 3000 is blocked it would increment to try to find a free port.

**Comment by Steven-lim1412** [comment]
The above will work if you have a define port, but how do you set it when the port is dynamic? like in the case of heroku where you will need to run a command to get the port. process.env.PORT. Where can we set this?
