### ISSUE TITLE
How can I link to other pages and keep localization?

### ISSUE THREAD

**Issue by kikobr** [Gottwik/Enduro#131]
Hi there! Really liking Enduro.js so far, it's awesome!

Well, I have 2 pages with 2 cultures (pt & en), and I understood that each culture adds a prefix in the URL. 

How can I create a link from "/page-1" to "/page-2" that will work no matter if the prefix is "/pt" or "/en"?

**Comment by CosmoMyzrailGorynych** [comment]
Where do you place these links? 

It can be programmed in template files or just written in both translations as needed in content files.

**Comment by kikobr** [comment]
I'm trying to place them inside my template "page-1.hbs". Since I can't know for sure what locale is being applied, I don't know how I'm supposed to create a link to "page-2.hbs". I was hoping there would be an object to automatically apply the current locale.

Maybe I could do that by creating a custom helper that checks the URL, and if it matches a locale,   puts that prefix before the link. Is that the easiest way to accomplish that?

**Comment by CosmoMyzrailGorynych** [comment]
I'm not sure it is the easiest way, but yeah, I built such a feature by myself with helper functions:

**Template**
``` handlebars
{{#if _meta.culture}}
    {{#ifeq fullpath '/index'}}
        <a href="/{{_meta.culture}}/">{{linkTitle}}</a>
    {{/ifeq}}
    {{#ifneq fullpath '/index'}}
        <a href="/{{_meta.culture}}{{fullpath}}/">{{linkTitle}}</a>
    {{/ifneq}}
{{else}}
    {{#ifeq fullpath '/index'}}
        <a href="/ru/">{{linkTitle}}</a>
    {{/ifeq}}
    {{#ifneq fullpath '/index'}}
        <a href="/ru{{fullpath}}/">{{linkTitle}}</a>
    {{/ifneq}}
{{/if}}
```

**Helpers** (`assets\hbs_helpers`)

``` javascript
/* global enduro */
enduro.templating_engine.registerHelper('ifeq', function (one, two, options) {
    return one == two? options.fn(this) : '';
});
enduro.templating_engine.registerHelper('ifneq', function (one, two, options) {
    return one != two? options.fn(this) : '';
});
```

Don't forget to replace `ru` in templates with your default language.

**Comment by kikobr** [comment]
Thanks!

**Comment by CosmoMyzrailGorynych** [comment]
Hey @kikobr, 
If your issue was solved, mark it as 'closed' for tracking purposes.

**Comment by kikobr** [comment]
Sorry, I forgot about that. Thanks again.
