### ISSUE TITLE
Can I change Admin labels?

### ISSUE THREAD

**Issue by kikobr** [Gottwik/Enduro#132]
When I add a key to the "/cms/index.js" object, it goes to the admin with that exact key name. Is there any way I can customize this? 

Let's say my key is "firstName" but I want to display it as "Your Name". Is this possible?

Thanks for the great work.

**Comment by rnlambert7** [comment]
It appears this issue should be in the enduro admin repo. Specifically where crumbs are located is here inside the angular app portion of the admin: https://github.com/Gottwik/enduro_admin/blob/d574491f4ec4bdc9ec0cc823cfb0c2d4c93c719a/assets/js/views/cms_edit.html#L18

**Comment by rnlambert7** [comment]
This issue is related to the admin interface, I've gone ahead and opened a new issue referenced above since I'm interested in this as well.

**Comment by kikobr** [comment]
Thanks @rnlambert7, I'm closing this one

**Comment by Gottwik** [comment]
sure, just do:

```
{
	$first_name_label: 'What\'s your name',
	first_name: 'Kiko',
}
```

**Comment by Gottwik** [comment]
this is a standard feature, just do:
```
{
	$first_name_label: 'What\'s your name',
	first_name: 'Kiko',
}
```
