### ISSUE TITLE
Please remove bower from enduro scaffolding and theme manager :c

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#133]
Why?

1. It causes bugs on Windows ([post-install script](https://github.com/Gottwik/Enduro/blob/cd4c61d7c48c86eae3fa70c3166323509ee663f4/scaffolding/minimalistic/package.json#L7) always fails; also see #128 );
2. It is not needed in a new project;
3. Not all people choose bower as a package manager for frontend libs;
4. Not all people need such at all;
5. It is considered as 'deprecated' and superceeded by yarn.

**Comment by Gottwik** [comment]
+1. Care to pull request?

Should we remove bower or replace it with yarn? What's your view on this?

**Comment by CosmoMyzrailGorynych** [comment]
So far, I don't see any reason to tie any package manager to enduro. But since enduro itself has little to do with frontend development, I think that there should be no such managers by default.

Perhaps someone else will express a different opinion.
