### ISSUE TITLE
Flat db tests fail on Windows

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#134]
```
> enduro@1.4.38 test C:\Users\Космо\Documents\Enduro
> mocha --recursive --bail

  Abstractor
    √ should register all the abstractors

(…)

  flat db object feature detection
    √ should detect if flat object has a page associated
    √ should detect that if flat object is deletable or not
    √ should convert flat object path into a valid url
    1) should convert flat object path into a valid file path


  68 passing (9s)
  1 failing

  1) flat db object feature detection should convert flat object path into a valid file path:

      AssertionError: expected 'gallery\\index' to equal 'gallery/index'
      + expected - actual

      -gallery\index
      +gallery/index

      at Context.it (test\flat_test\flat_test.js:251:56)
```

I will try to fix this this night

**Comment by CosmoMyzrailGorynych** [comment]
@Gottwik , this function has some inconsistency on Windows — it uses `/` instead of `\` if a page is a generator's file. Shall this function return URL or a file's path? I can't determine if this function should return  `these/paths/everywhere` or `these\paths\on\Windows`.

https://github.com/Gottwik/Enduro/blob/cd4c61d7c48c86eae3fa70c3166323509ee663f4/libs/flat_db/flat.js#L197-L215

**Comment by Gottwik** [comment]
I fixed these flatdb tests.

I struggled to fix the whole suite though. rimraf(dependency to delete stuff) is failing on windows as well, not sure what to do with this.
