### ISSUE TITLE
Referencing objects in the admin's JS files

### ISSUE THREAD

**Issue by mirkea** [Gottwik/Enduro#146]
Sorry if the title is misleading but I'm not sure how I should phrase this. Here is the scenario I have:

I want to make a simple website (with one or more pages) that are made up of sections of different types (hero, pictures list, etc). All sections are defined as different files, but I want them all to have some things in common, such as a slug. Even if I make it a one pager, the slugs are still needed, so I can make the URL change on scroll to reflect the current section.

The slug itself would be a simple field, but I want it to also have a tooltip/info, giving the user some hints about what this is for and how it should look. So the slug 'component' I need is a field plus info.

Now, I see two approaches here: 

1. add the slug as individual fields in each section but the slug info is defined somewhere else
2. make the slug field + info as a template, referenced in each section

On the first approach I got stuck on getting the actual info from a global object ( I know `@@global` can reference an object but I don't know how to get the actual data from it, so I can write stuff such as 

**cms\global\globals.js** 
```
{
   tooltips: {
      slug: "This should only include lowercase letters, numbers or '_' and it will be used for....... blah blah ",
      visible: "This section will not be displayed on the site, but its content will still be available for later use"
   }
}
```

**cms\global\templates\sections\clients.js:**
```
{
   header: "",
   $slug_info: "@@global.tooltips.slug"
   slug: ""
}
```

The second approach (making a separate component) feels a bit more elegant, especially  as it will allow for more complex structures, but I sort of got stuck there too. With something like this

**cms\global\templates\admin\slug.js**
```
{
   slug: {
       $slug_info: "This should only include lowercase letters, numbers or '_' and it will be used for....... blah blah",
      slug: "",
   }
}
```

**templates\sections\clients.js**
```
{
   header: "",
   $slug_templatitator: "@@global.slug",
   slug: []
}
```
This obviously will make slug into an array in the clients section, when I want only one instance of it. Using `slug: {}` doesn't seem to work. I can use `$slug_min` and `$slug_max: 1` so I can only have one slug element per section ( as needed) but the user would have to click the "+" button first, when instead the option should be there from the start.

I hope this makes sense. 
PS: Enduro seems pretty awesome and it has the potential to be my favorite CMS (and I've used a lot of them).

**Comment by CosmoMyzrailGorynych** [comment]
Hey @mirkea, I use a second option as it makes the best experience both while creating content in admin panel and while writing templates for them, but yeah, there is no way to make a default linked option if you need such. If I created such template cms files for someone, I would use a predefined object in it, like this:

``` js
{
   header: "",
   $slug_templatitator: "@@global.slug",
   slug: {
      $slug_info: "This should only include lowercase letters, numbers or '_' and it will be used for....... blah blah",
      slug: 'blah'
   }
}
```

So users get one block to fill in new files, but certainly this isn't quite DRY. Another option is to create a small admin script so it creates a missing object automatically.

**Comment by CosmoMyzrailGorynych** [comment]
Sorry, I read your issue diagonally and missed the main point of using globalizer and templatitators. :sweat_smile: 

I think you can create a special component type that just returns a plain text so it can be used as help sections. Then you can place them in objects, templates, or as is in content files, on the top level.

So you could create a file `\assets\admin_extensions\helpnotice.js` and add some styles:

``` handlebars
<div class="form-control \{{size}} help-notice">
	<span>\{{context[terminatedkey]}}</span>
</div>
```

Then you could write it in cms as following:
``` js
{
   slug: 'lalaland',
   slug_info: 'This should only include lowercase letters, numbers or '_' and it will be used for....... blah blah',
   $slug_info_customtype: 'helpnotice'
}
```

**Comment by mirkea** [comment]
@CosmoMyzrailGorynych I tried that and it seems to be a solid solution.  Thanks a lot

**Comment by CosmoMyzrailGorynych** [comment]
:+1: 

@mirkea If you don't have additional questions, please close the issue for tracking purposes.
Also I think the issue may be called 'Adding tooltips and help notices to admin fields' or so.

**Comment by mirkea** [comment]
sure thing
