### ISSUE TITLE
Install failure on Debian

### ISSUE THREAD

**Issue by jours** [Gottwik/Enduro#152]
Clean install of Debian 9; same behavior on another Debian 8 workstation.

sudo npm install enduro -g

fails to install.  

Same behavior if I try to actually install as root.  Interestingly, it does install successfully as my regular user to the local folder if I leave off the "-g" switch.

Output is this:

npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/enduro -> /usr/lib/node_modules/enduro/cli.js

> uws@0.14.5 install /usr/lib/node_modules/enduro/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> ttf2woff2@2.0.3 install /usr/lib/node_modules/enduro/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/enduro/node_modules/ttf2woff2/.node-gyp"

> node-sass@4.5.3 install /usr/lib/node_modules/enduro/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node
Download complete .] - :
Binary saved to /usr/lib/node_modules/enduro/node_modules/node-sass/vendor/linux-x64-48/binding.node

> svgicons2svgfont@7.0.2 postinstall /usr/lib/node_modules/enduro/node_modules/svgicons2svgfont
> npm run metapak --silent

glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
    at Error (native)
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'\n    at Error (native)',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/enduro/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "enduro" "-g"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! svgicons2svgfont@7.0.2 postinstall: `npm run metapak --silent`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the svgicons2svgfont@7.0.2 postinstall script 'npm run metapak --silent'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the svgicons2svgfont package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run metapak --silent
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs svgicons2svgfont
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls svgicons2svgfont
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jours/Projects/Test/npm-debug.log
npm ERR! code 1

Full debug log attached.

[npm-debug.log](https://github.com/Gottwik/Enduro/files/1361465/npm-debug.log)

**Comment by CosmoMyzrailGorynych** [comment]
#151

Make sure you have build tools installed: `sudo apt-get install -y build-essential`

If this doesn't work, try installing enduro with `--unsafe-perm` flag.

It seems that a bunch of packages cannot be installed globally (at least `node-sass` can't). I wonder why they began to show errors in recent time on different node/npm versions, while still being local dependencies. The latest enduro update on npm occured in August.

You have node v6.11.4, right?

**Comment by jours** [comment]
Yes, node v6.11.4 and build-essential installed.

Adding the --unsafe-perm flag worked.  So for posterity, installing on Debian 8+, and I suspect other environments, will require:

sudo npm install enduro -g --unsafe-perm

at least for the time being, contrary to what is in the install documentation.

**Comment by CosmoMyzrailGorynych** [comment]
Still it _shouldn't_  work like that. It was ok without `--unsafe-perm` before.

:pensive:

**Comment by ccoffee** [comment]
Same problem brand new Ubuntu 16.04 server, Node 7.10.1, NPM 4.2.0

$ enduro create helloworld
Unhandled rejection Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/enduro/node_modules/node-sass/vendor'

Tried reinstalling, rebuilding node-sass with npm rebuild. No go.
