### ISSUE TITLE
Using enduro inside electron project?

### ISSUE THREAD

**Issue by reneisrael** [Gottwik/Enduro#155]
Is it possible? Can you help me with directions? A boilerplate maybe?
Thanks in advance.

**Comment by CosmoMyzrailGorynych** [comment]
It must be possible, but there isn't any boilerplate for nw.js or electron.

You can launch Enduro programmatically using such code:

``` js
/* launch in dev mode */

var enduro_instance = require('enduro')

enduro_instance.init({ flags: {} })
.then(() => {
	enduro.actions.developer_start()
})
```
``` js
/* launch in production mode */

const path = require('path')
const enduro_instance = require('enduro')
const project_path = cli_arguments.path ? path.join(process.cwd(), cli_arguments.path) : ''

enduro_instance.init({ project_path: project_path })
.then(() => {
	enduro.flags = {}
	enduro.actions.start()
})
```

These snippets are mainly copied from [enduro's CLI commands](https://github.com/Gottwik/Enduro/tree/master/cli_commands).

**Comment by rnlambert7** [comment]
Did that work for you @reneisrael ?

**Comment by reneisrael** [comment]
Haven't tried yet, I've been busy with my bridezilla ;)
Hope to work with it next month.

**Comment by Gottwik** [comment]
Very exciting, let us know if you worked this out.
