### ISSUE TITLE
S3 Bucket ACL change after first pack

### ISSUE THREAD

**Issue by psander-com** [Gottwik/Enduro#166]
Hi there, i recently switched to s3 remote storage and found a strange behavior after the first pack.

When you create a bucket for the project and create a folder, you have to make it public. But the public folder went closed after you run the first time `$ enduro juice pack`. After some research, i found a solution by setup the `ACL: 'public-read'` in the s3Params.

If you can reporduce this, i can/have PR ready for you. 

Thanks for this awesome tool. Like it!

PS: It would be nice to use process.env for the S3 credentials and regions for automated deployments in some enviroments. I can include this in the PR.

**Update**
https://github.com/Gottwik/Enduro/pull/172

**Comment by rnlambert7** [comment]
Agreed. I ran into this earlier this week and meant to put in this very issue, but you beat me to the punch. ;)

**Comment by Gottwik** [comment]
Thank you for researching this and fixing this by #172 . Feel free to reopen if any more issues arise.
