### ISSUE TITLE
Heroku Cycling causing data loss

### ISSUE THREAD

**Issue by dannydel** [Gottwik/Enduro#169]
Hello,

I currently have an enduro js site setup on Heroku, but I am finding that after I add and publish from the admin side my data eventually gets reset to what I pushed before adding the content through admin. This, I believe, is from Heroku cycling the dynos. Does anyone have an enduro site live on Heroku and finding the same thing to be happening? Is there a fix or should I use another service like Netlify?

Thanks in advance!

**Comment by Gottwik** [comment]
do you have juicebox enabled?

**Comment by dannydel** [comment]
No, I have revisited documentation and realize that is now what I need. Thank you for your answer!

 Is there a way to incorporate Dropbox instead of aws s3?

**Comment by Gottwik** [comment]
:-) the file system is completely decoupled, all you need to do is
implement upload and download. Feel free to pullrequest I can help you with
it.

**Comment by dannydel** [comment]
Awesome! I'll pull and see if can get that working. Thanks again!

**Comment by Gottwik** [comment]
I'll close this ticket. @dannydel feel free to reopen or ask more questions :-)

**Comment by dannydel** [comment]
Will do! I've been a little busy at work but I am hoping once things calm down I can sit down and figure out wiring up DropBox! I'll let you know if I have any questions.

**Comment by karneaud** [comment]
did you ever get around to doing this @dannydel ?

**Comment by dannydel** [comment]
No, I sadly have had no time. I forked the repo but never got to
implementing a connection to another service.
