### ISSUE TITLE
Q: Create pagelist for services

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#182]
I want to create "**services**" page  (With dynamic page list generator).

**I follow this tutorial:**
http://www.endurojs.com/blog/how-to-make-a-blog-with-endurojs
Works great!! very easy to set blog like this. 

## Q
If I want to make the same idea for "**services**' generator - what I should change?

I try to change `/assets/hbs_helpers/blog.js` to `/assets/hbs_helpers/services.js` and ctr+f change anytime I find blog change to services + change to this code:
```
{{#services}}
    {{#each this}}
        <article>
            <h2>{{services_entry.title}}</h2>
            <p>{{{services_entry.text}}}</p>
            <a href="/services/{{page_slug}}">Read more...</a>
        </article>
    {{/each}}
{{/services}}
```
Not work (No output)

**Comment by Gottwik** [comment]
Could you just reuse the blog helper to create the services page?

Did you create the generator template(`/pages/generators/services.hbs`) and some context files(`/cms/generators/services/ezras_service.js`)?

**Comment by Ezra-Siton-UIX** [comment]
Yes. What do you mean by saying "reuse the blog helper" 

The structure is ok (I have list of services under `/cms/generators/services/`).

**Comment by Gottwik** [comment]
seems to be working for me :-/

![image](https://user-images.githubusercontent.com/277311/33136881-a11743a4-cfa6-11e7-8b84-07787b23786d.png)


Hey, you can log stuff out from the helper and also from the template by doing
```
{{#services}}
{{log this}}
{{#each this}}
```

**Comment by Ezra-Siton-UIX** [comment]
Yes. I find something really weird - this works only when the name is diffrence.
When i change the name of the page list to "services" I dont get any output (wierd but this is whats happen)

**Comment by Ezra-Siton-UIX** [comment]
Also (please check this) - on version:
1.4.41

When i create blog page - the "folder" icon in the admin dissapear (look like this):

Good (option to add post)
![image](https://user-images.githubusercontent.com/16711871/33142565-abdec9c4-cfbf-11e7-89fa-4f4f2ea9a1de.png)

When i change the blog list page to "blog" no "folder-icon" option to add posts by admin:
![image](https://user-images.githubusercontent.com/16711871/33142778-4cf80c08-cfc0-11e7-8f55-2c3555ccee4d.png)

**Comment by Ezra-Siton-UIX** [comment]
I will check this again and will add post. Maybe this was cache issue. Thanks
