### ISSUE TITLE
How to update to enduro 1.4.42

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#183]
I work with:
1.4.41  | Windows

1. run `npm update -g enduro`
2. run `enduro --version`
still output: `1.4.41`

https://www.npmjs.com/package/enduro

npm: 3.10.10
node: v6.11.2

**Comment by CosmoMyzrailGorynych** [comment]
Cannot reproduce it on Windows:

```
PS F:\Enduro\Enland> enduro --version
1.4.42
PS F:\Enduro\Enland> npm -v
5.5.1
PS F:\Enduro\Enland> node -v
v8.9.1
```

It is also ok on npm site:
![image](https://user-images.githubusercontent.com/3174357/33300980-bd395114-d44f-11e7-8c0a-fe830088098f.png)

@Ezra-Siton-UIX , are you facing this issue now? Do you have a fork of enduro `npm link`-ed to your system?

**Comment by Ezra-Siton-UIX** [comment]
Thanks
i run:
npm link
npm install enduro -g

Now works fine. Do you know about any "changelog" doc ?
