### ISSUE TITLE
Suggestion: Field Notes and Descriptions

### ISSUE THREAD

**Issue by rnlambert7** [Gottwik/Enduro#185]
**Suggestion 1**
New Field Addition: `_note`.
Usage:
```
example_field_type: 'text',
example_field_note: 'Enter a description for this section',
example_field: ''
```
And it would show the note around the text field or below it so that you can note what fields are for users or what they should be entering.

**Suggestion 2**
Similarly it would be nice to have a text box as it's own field that would be good for larger descriptions. For instance if I need to give context to a field, etc. Instructions that I could not automate. I find with clients that aren't as tech friendly they always ask for something like this and  on other CMS's I usually have to fake it in. If this is a harder thing to do, it would at least be useful to set a field as uneditable. Then I could do a markdown field, remove the frame, and then set to uneditable.

**Comment by rnlambert7** [comment]
**Suggestion 3**
Adding in a third suggestion. I realize this a lot for one issue, however felt they were all related.

Add titles and subsections in cms. For instance if I had a field that would break up the cms fields and insert say a large title for a subsection.

**Comment by CosmoMyzrailGorynych** [comment]
**Suggestion 1:** afaik there is no such notes yet, but they can be replaced by the next solution ⬇️ 

**Suggestion 2:** https://github.com/Gottwik/Enduro/issues/146#issuecomment-332480452

**Suggestion 3:**
You can add headings by inserting additional fields with 'title' type:
``` js
{
  title_settings: 'Settings',
  $title_settings_type: 'title',
}
```

It is also a good practice to group related fields in objects. They can also be collapsed if provided with expander flag: [example from Mirror theme](https://github.com/Gottwik/enduro_mirror/blob/master/cms/index.js#L81)

**Comment by rnlambert7** [comment]
**Suggestion 1**: Agreed

**Suggestion 2**: So I attempted to duplicate this, but I may be missing information. It looks like you created a custom type entirely, which I was unaware I could do. I attempted to place the `/pages/custom_types/helpnotice.hbs` in my project along with the same CMS fields in a CMS page, however that did not work. Next I added `/pages/custom_types/helpnotice.hbs` to my enduro_admin clone I npm linked, and that didn't add it either. Is there additional logic that needs to go somewhere to create and register the custom type?

**Suggestion 3**: Thanks :) I did not think to just move my titles around and see if they'd be placed anywhere other than the top. Also, yes using the expanders and objects.

**Comment by Ezra-Siton-UIX** [comment]
I love the idea of Concrete5 - you have option to add description than in the form you see  "?" icon - tooltip (on hover you see "please add main image bla bla"). That way the admin is more clean.

**Comment by rnlambert7** [comment]
So Bricks solve this issue. I was working off the old style of custom_types before, and attempted to implement it after it was removed and replaced with bricks. Learning from the enduro_quill brick I can make the custom types I want, so this is no longer an issue.
