### ISSUE TITLE
Suggestion: Ability to pass configuration options to bricks

### ISSUE THREAD

**Issue by ericgla** [Gottwik/Enduro#186]
Glad to see that a plug-in system has been added to Enduro.  I'm sure it's already on your radar, but it would be nice to pass configuration options to a brick.  In the case of the quill wysiwyg editor, there is no way to configure the options on the toolbar.

**Comment by Gottwik** [comment]
yup, will do this

**Comment by ericgla** [comment]
I actually got this working over the weekend with enduro_quill.  It was as simple as adding a config object to the context for the element, then when compileProvider is called within the plugin, merge the default config with scope.context.config.

I can do a pull request on enduro_quill, but wanted to check to see if you had a different plan for implementing brick configuration.

**Comment by Gottwik** [comment]
Hey Eric, pull requests are always welcome and appreciated.

In the meantime, I got it done by passing whatever configuration you put into enduro.json to admin's javascript: 

settings:
https://github.com/Gottwik/enduro_samples/blob/master/enduro_quill/enduro.json

getting the config by brick:
https://github.com/Gottwik/enduro_quill/blob/master/assets/inject_quill_to_admin.js#L14

feel free to improve on that if you get any ideas 👍

**Comment by rnlambert7** [comment]
Closed, but fantastic. Would be great to get that into the docs on the site. Going to update my brick now that I see this!
