### ISSUE TITLE
Search for a way to get url_slug

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#188]
I want to use the file name as $var to create breadcrumbs link. Thier is some way to get this value? (The name of the file under pages)

I saw an example of this idea here (under "Create blog list page")
https://www.endurojs.com/blog/how-to-make-a-blog-with-endurojs

**Comment by rnlambert7** [comment]
Hey Ezra,

So in the handlebars template `this` holds everything you can access for the page. At the top level it includes the fields from the page itself, the global object, and _meta. On a page do `{{log this}}` and restart your enduro server and check the terminal to see everything. Dive deeper and you should have all the pieces there. If you purely want the slug/pagename then you can do `{{_meta.pagename}}`.

Hope this answers your question.

**Comment by Ezra-Siton-UIX** [comment]
**WOW** thanks!!, works nice. Where you find this details under handlebars docs?
