### ISSUE TITLE
Fedora install failed

### ISSUE THREAD

**Issue by CorentinDy** [Gottwik/Enduro#196]
Hi,
I've just find Enduro and wanted to try it.
I can't install Enduro.

Fedora 26 - Node 8.9.3 - npm 5.6.0

Here is the log for npm install
[enduro.log](https://github.com/Gottwik/Enduro/files/1597803/enduro.log)

**Comment by rnlambert7** [comment]
Hi @CorentinDy 

First, in the future it would be helpful if you could post this inside 
```
a nice clean code snippet
```
so we can read it here instead of opening a file to view. (Safety and security reasons as well)

Secondly, it looks like you are getting permission errors during the install. Not sure if its related to Enduro's installation specific to Fedora, or if you have permission issues on your side.

**Comment by CosmoMyzrailGorynych** [comment]
@rnlambert7 then it is related to the whole Linux ecosystem :) There are processes spawn as by regular user even if installation is done with administrator's rights. But I don't face this issue with other global packages like gulp. So yeah, this might be a problem with Enduro.

I'm on Fedora too and will try to make a workaround for **CorentinDY** soon. I installed it on Ubuntu 16 before, but it's a bit more complicated on Fedora.

**Comment by CosmoMyzrailGorynych** [comment]
@CorentinDy, I assume that you never done any steps like described [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions) (don't worry, nobody does it 😆). Type
```
npm root -g
```
to get the folder where npm installs modules. It is `/usr/lib/node_modules/` for me, but don't forget to replace it below if it differs.

Then run
```
sudo chown $USER /usr/lib/node_modules/
npm install enduro -g --no-bin-links
sudo chown root /usr/lib/node_modules/
sudo ln -s /usr/lib/node_modules/enduro/cli.js /usr/bin/enduro
```
What I'm actually doing:
1. Change owner of `/usr/lib/node_modules/` to the current user.
2. Install enduro globally without root rights and telling npm that it shouldn't create symlinks to enduro's CLI. I do it manually later.
3. Then change owner of `/usr/lib/node_modules/` to the root user so nobody notices it.
4. Lastly, I create a symlink to enduro's CLI so you can run `enduro` anywhere.

I'm using Fedora 27 on GNOME, my NPM is 5.6.0, and node itself is 9.4.0

**Comment by xXACCEXx** [comment]
I used NVM to maintain node versions. Makes it easy to update and what not.

NVM makes its own modules directory, which is obvious when running `npm root -g` from @CosmoMyzrailGorynych's post.

I changed ownership of the node_modules dir shown from `npm root -g`, then could install fine.

**Comment by CorentinDy** [comment]
CosmoMyzrailGorynych's solution worked perfectly ;)
