### ISSUE TITLE
Static Hosting page shown when navigating to localhost:5000/admin locally

### ISSUE THREAD

**Issue by mdxprograms** [Gottwik/Enduro#199]
I'm running `enduro dev` after doing `enduro theme mirror` setup.
When I navigate to `localhost:5000/admin` I get the static hosting page.

The second option is what I am doing, but it still shows the static page.

I'm using Ubuntu xenial LTS

Any ideas here?

**Comment by Gottwik** [comment]
what's the static hosting page? do you get the same thing as going to localhost:5000?

Could you try doing `enduro start` and going to locahost:5000/admin to see if it does something different?

I just tried it and I get the admin as expected. Could it be you are running an outdated(possibly buggy) version of enduro? Could you try updating(`npm i enduro -g`)?

**Comment by mdxprograms** [comment]
no clue what is different now... I re-installed it and ran `enduro theme` and it worked just fine... I think last time I did `enduro theme mirror` instead. Would that cause any different results on generation? I don't remember the directory looking the same then :(
