### ISSUE TITLE
Use env variables in enduro_secret.json

### ISSUE THREAD

**Issue by apmitchell** [Gottwik/Enduro#200]
## How do we use node env variables in the enduro_secret.json file?

Per http://www.endurojs.com/docs/using-s3-as-filesystem  

The docs say we can use env variables in this json file.  I think I am missing something either very simple or this is actually not possible.

<img width="1176" alt="screen shot 2018-01-04 at 7 18 53 pm" src="https://user-images.githubusercontent.com/5396521/34594150-5683a378-f184-11e7-9c3e-b11ba7366650.png">

**Comment by rnlambert7** [comment]
I believe this is saying you can use `enduro_secret_json` OR use an `.env` file. As in you would create your own `.env` file and then use `dotenv` node package elsewhere in the project where needed.

**Comment by apmitchell** [comment]
Ah, I see.  Thanks @rnlambert7 

Might be nice to make this optionally a JS file so we could use process.env in it natively then have the framework parse it to JSON.
