### ISSUE TITLE
new Project No such file or directory

### ISSUE THREAD

**Issue by rkmax** [Gottwik/Enduro#202]
I have just installed `npm i -g enduro`

 then try to different approches (I dont know what is the correct one)

## First Approch
-  `$ enduro create helloworld-1; cd helloworld-1`
-  `$ enduro dev`

I got 

    ENOENT: no such file or directory, open '/home/rkmax/helloworld-1/_generated/_prebuilt/brick_admin_settings.js'

## Second approch
-  `$ enduro theme`
- answered all the question, the project name was `helloworld-2`

then I got the same error

    ENOENT: no such file or directory, open '/home/rkmax/helloworld-2/_generated/_prebuilt/brick_admin_settings.js'

I'm using 

- enduro 1.4.44
- node 9.2.0
- GNU/Linux 4.14.5-1-ARCH x86_64

**Comment by Gottwik** [comment]
yup, my bad, broke stuff.

just pushed a fix, could you update enduro(`npm i enduro -g`) and confirm this is fixed?

**Comment by rkmax** [comment]
Thank you for your outstandingly fast response. I'll test the new version and back to you

**Comment by rkmax** [comment]
@Gottwik  Pal, it's working!! thank you. I'll play around a bit

**Comment by Gottwik** [comment]
my bad for breaking stuff. Anyway, happy to help 😄

**Comment by CosmoMyzrailGorynych** [comment]
@Gottwik but there isn't 1.4.44 or 1.4.45 😐 https://github.com/Gottwik/Enduro/blob/master/package.json
