### ISSUE TITLE
assets dont get included on _generated folder

### ISSUE THREAD

**Issue by rkmax** [Gottwik/Enduro#207]
I'm just droping some bunch of js, css and images on the assets folder, but they dont get copied to the _generated folder

**Comment by rnlambert7** [comment]
Hi, have you tried doing this while running enduro in development mode?

I just tested out dropping images into the assets folder in both dev and production modes. In production the assets don't get moved over. However in dev, they are automatically copied over.

To save you a trip back to the docs, CLI commands for both:
`enduro dev` for Development
`enduro start` for Production

Hope this helps!

**Comment by rkmax** [comment]
thanks for the info!
