### ISSUE TITLE
Enduro js - Changlog

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#215]
Their is any changelog file ?

Something like this:
https://github.com/uikit/uikit/blob/master/CHANGELOG.md

I really like to follow new **features** and **ideas** added & **bugs** fixed between versions.

**Comment by CosmoMyzrailGorynych** [comment]
For now, I have to look through [commit list](https://github.com/Gottwik/Enduro/commits/master) 😢

It would be great if releases could contain information about changes as described in [Github's blog](https://github.com/blog/1547-release-your-software).

We could also use some sort of automated changelog generation, and such approach requires proper notation of all commits and merges. I used approach like in [this generator on npm](https://www.npmjs.com/package/generate-changelog) for my software, and it was quite handy.
