### ISSUE TITLE
production build remove source maps and minify js and css?

### ISSUE THREAD

**Issue by daveswebdesigns** [Gottwik/Enduro#220]
Hi, I am finished a project now, but I realise all my javascript files have unwanted sourcemap information in them. Also, I would like to minify and concatenate my js and css files for production. 

So, is there a way to turn off the sourcemaps? And I see someone already asked about how to minify css and you said it might be possible with gulp in the app.js file. Is there any example anywhere of how to use gulp in that file? 

Thanks!

**Comment by Ezra-Siton-UIX** [comment]
Hi. I also add related topic
https://github.com/Gottwik/Enduro/issues/168

## CSS
About - CSS I hope this idea will be in the core (.min). 

## JS
About JS - one "huge" JS is not always faster (Because you can use defer or async for JS files above the fold) + It's more complicated + I use most of the time CDns' 
https://gtmetrix.com/why-use-a-cdn.html

## source maps
Remove the map file. Anyway this is great for debbuging why you want to remove this?
Read related topic (Not enduro but react)
https://github.com/facebook/create-react-app/issues/2005

**Comment by daveswebdesigns** [comment]
Hi, thanks for getting back to me.

I was building a very small site, so size and speed were most important.
That's why I concentrated my js (35kb total from 6 files loads much faster
concatenated)

Also, sourcemaps are great for debugging but were adding more than 100%
extra filesize, no good for production!

It's all good though, I ended up just creating my own gulpfile in the root
to achieve everything I needed from the source.

Thanks, Dave




On 28/01/2018 9:54 PM, "Ezra siton" <notifications@github.com> wrote:

Hi. I also add related topic
#168 <https://github.com/Gottwik/Enduro/issues/168>
CSS

About - CSS I hope this idea will be in the core (.min).
JS

About JS - one "huge" JS is not always faster (Because you can use defer or
async for JS files above the fold) + It's more complicated + I use most of
the time CDns'
https://gtmetrix.com/why-use-a-cdn.html
source maps

Remove the map file. Anyway this is great for debbuging why you want to
remove this?
Read related topic (Not enduro but react)
facebook/create-react-app#2005
<https://github.com/facebook/create-react-app/issues/2005>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gottwik/Enduro/issues/220#issuecomment-361053998>, or mute
the thread

**Comment by Ezra-Siton-UIX** [comment]
Nice. If you solve this issue - close the topic. 
You can add your code example (Gulp) For other users.

**Comment by daveswebdesigns** [comment]
Hi, here's my gulpfile.js in case it can help others:

`var http = require('http');
var gulp = require('gulp');
var csso = require('gulp-csso');
var concat = require('gulp-concat');
var jsmin = require('gulp-jsmin');
var sass = require('gulp-sass');
var bulkSass = require('gulp-sass-bulk-import');
var rename = require("gulp-rename");
var ecstatic = require("ecstatic");
var babel = require('gulp-babel');
var gulpif = require('gulp-if');
var lr = require('gulp-livereload');
var sourcemaps = require("gulp-sourcemaps");
var livereloadport = 35729,
	serverport = 5001;


gulp.task('dev_css', function(){
	gulp.src("./assets/css/main.scss")
		.pipe(bulkSass())
		.pipe(sourcemaps.init())
		.pipe(sass({includePaths: ['./assets/css']}).on('error', sass.logError))
		.pipe(sourcemaps.write())
		.pipe(rename("styles.css"))
		.pipe(gulp.dest("./_generated/assets/css/"))
		.pipe(lr());
	console.log("dev CSS complete");	
});

gulp.task('dist_css', function(){
	gulp.src("./assets/css/main.scss")
		.pipe(bulkSass())
		.pipe(sass({includePaths: ['./assets/css']}).on('error', sass.logError))
		.pipe(csso())
		.pipe(rename("styles.css"))
		.pipe(gulp.dest("./_generated/assets/css/"))
		.pipe(lr());
	console.log("dist CSS complete");		
});

gulp.task('compile_js', function(){
	gulp.src(['./assets/js/libs/*.js', './assets/js/main.js'])
		.pipe(gulpif('*main.js', babel({presets: ['env']})))
		.pipe(concat('scripts.js'))
		.pipe(jsmin())
		.pipe(gulp.dest('./_generated/assets/js/'))
		.pipe(lr());
	console.log("JS Complete");
});

gulp.task('watch_css', function(){
	gulp.watch("assets/css/**/*", ['dev_css']);
});
gulp.task('watch_js', function(){
	gulp.watch("assets/js/main.js", ['compile_js']);
});

gulp.task('serve', function() {
	//Set up your static fileserver, which serves files in the build dir
	http.createServer(ecstatic({ root: __dirname + '/_generated' })).listen(serverport);
	//Set up your livereload server
	lr.listen();
  });


gulp.task('default', ['dev_css', 'watch_css', 'compile_js', 'watch_js', 'serve']);
gulp.task('publish', ['dist_css', 'compile_js']);
`

It's not super pretty but it worked for me. If anyone has any questions, they can message me.
