### ISSUE TITLE
Enduro blog pagelist - multilingual output problem

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#223]
`version 1.4.45 // windows10`

related topic: [How to create a blog with enduro.js](https://www.endurojs.com/blog/how-to-make-a-blog-with-endurojs)

I work on [multilingual site](https://www.endurojs.com/docs/multilingual-support) - "The problem" The output `always `show the main language when i trying to create pagelist 

```
### hbs
{{#blog}}
    {{#each this}}
        <article>
            <h2>{{blog_entry.blog_title}}</h2>
            <p>{{{blog_entry.blog_text}}}</p>
            <a href="/blog/{{page_slug}}">Read more...</a>
        </article>
    {{/each}}
{{/blog}}
```
### CMS:
```
{
    blog_title: 'This is a hello blog entry',
    blog_text: 'You just learned how to create a blog with enduro.js',
    $blog_title_he: 'שלום',
    $blog_text_he: 'פירוט',
}
```
Always output `blog_title` & `blog_text` (Ignore `$blog_text_he` and  `$blog_title_he`). In the post-page himself the output is ok.

**Comment by lehn85** [comment]
I also have this problem. After some times checking, I think it is because we don't have a blog.js file in __/cms__. The context is generated by Handlebars helper __/hbs_helper/blog.js__. 

In __/libs/page_rendering/page_renderer.js__, function __page_renderer.prototype.render_file_by_context__:
``
rendered_page = template(babel.culturalize(context, culture))
``

First, Babel try to culturalize, but context is empty (because /cms/blog.js doesn't exist).
And then, Handlebars parse template without considering culture. And here the default data is generated by Handlebars helper __/hbs_helper/blog.js__

I think we can have a workaround:
- use abstractor to render list of blog entries in /cms/blog.js
- modify Handlebars helper __/hbs_helper/blog.js__ to generate correct data depends on which culture is parsed.

**Comment by lehn85** [comment]
I did a workaround like this:
Create an abstractor __/app/abstractors/blog_enumeration.js__
```
// placeholder abstractor
var abstractor = function() {}

// vendor dependencies
var _ = require('lodash')
var Promise = require('bluebird')

abstractor.prototype.init = function(context) {
    return new Promise(function(resolve, reject) {

        // initialize abstractor
        resolve()
    })
}

abstractor.prototype.abstract = function(context) {
    return new Promise(function(resolve, reject) {

        // only if we mark it as a markdown doc
        if (context.blog_entry_enumeration) {            
            context.$page_hidden = true;
            var pages;

            // get all cms
            return enduro.api.pagelist_generator.get_cms_list()
                .then((pagelist) => {
                    var get_content_promises = []
                    pages = _.chain(pagelist.structured.blog)
                        .filter((o) => { return typeof o === 'object' }).value(); // filter pages only

                    for (page_id in pages) {
                        var page = pages[page_id]

                        function get_content(page) {
                            get_content_promises.push(enduro.api.flat.load(page.fullpath).then(
                                (content) => {                                    
                                    content.html_doc = undefined;//skip html_doc to save memory                                  
                                    page.content = content;
                                }));
                        }

                        get_content(page);
                    }

                    return Promise.all(get_content_promises);
                })
                .then(() => {
                    pages = _.chain(pages)
                        .sortBy('content.$date_value').reverse() // sort by date
                        .filter((page) => { return page.content.published }) // remove unpublished
                        .value();

                    context.pages = pages;

                    return resolve();
                });
        }

        return resolve();
    });
}

module.exports = new abstractor()
```

Create a file __/cms/global/bloglist.js__ (or anything). Must be in /global or admin control will confuse between file /cms/blog.js and folder /generators/blog.
```
{
	blog: {
		blog_enumeration: true,
        }
}
```

Now abstractor automatically create field **pages** in this file

In __/pages/blog.hbs__
```
    {{#each global.blog.pages}}
        <article>
            <h2>{{blog_entry.blog_title}}</h2>
            <p>{{{blog_entry.blog_text}}}</p>
            <a href="/blog/{{page_slug}}">Read more...</a>
        </article>
    {{/each}}
```

**Comment by CosmoMyzrailGorynych** [comment]
Hey,
My Enblog theme probably works with multiple languages. You should probably look at its code: https://github.com/CosmoMyzrailGorynych/enblog_theme

If you still can't make it work I can assist you as I have a multilingual enduro site based on the same code

**Comment by TooDizzy** [comment]
Can't get this to work.
I have a page called _speakers_. This page loops through some content from a generator called _speaker_.
All the default content is displayed, but the translated content does not. The parent page (_speakers_) have working translation.

I looked at all the comments above, but haven't found a working solution yet. It seems a bit much to create new code for this. And didn't find a working solution with the enblog theme.

Any suggestions on how to get this working?

/Tue

**Comment by Ezra-Siton-UIX** [comment]
The library does not support anymore. Close the topic (Without solution).
