### ISSUE TITLE
Q: What is this {{slug label}} ?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#226]
The {{slug label}} convert this label:
`label: What is enduro`
### To
`what-is-enduro`

This is build-in helper? Or build-in handlebarsjs feature?

I find this idea her:
https://github.com/Gottwik/enduro_website/blob/master/pages/docs.hbs

**Comment by GitableRoy** [comment]
The **slug** in `{{slug label}}` is a hbs_helper provided by Enduro itself, not a default helper by Handlebars.  You can find the exact script location for the helper in Enduro's repository here:

https://github.com/Gottwik/Enduro/blob/master/hbs_helpers/slug.js

**Comment by Ezra-Siton-UIX** [comment]
@GitableRoy great! :) Thanks
