### ISSUE TITLE
BrowserSync Synchronize across multiple devices - External URL - HOW TO?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#228]
## External URL
In the past I work with this framework/starter:
https://developers.google.com/web/tools/starter-kit/

In **google-starter-kit**- their is - Cool feature - when I want I could open my `local site` on my mobile device with some i get `External URL` like "[http:://192.168.1.7:3000](http:://192.168.1.7:3000)" (I don't remember extcat the address).

This is useful if I want to check my local-site works on  **real mobile device**. Thier is a way to do this by Enduro? 

I think this is **browsersync** option related to my topic:
https://www.browsersync.io/docs/options#option-open

**Comment by CosmoMyzrailGorynych** [comment]
Hey @Ezra-Siton-UIX,

In fact, google starter kit just shows your local IP. Almost every node.js server, including enduro, can serve sites over local network. To do this, you should connect your PC and mobile phone to one WiFi network, then find out your local IP on PC, and write something like `192.168.XX.XX:3000` on your smartphone. I checked it and it works :)

On Windows, local IP can be found in control panel -> network adapter settings -> your connection -> info, or by typing this command: `ipconfig`

`ipconfig` has a row called 'IPv4 address', and that's what you need.

On Linux, GNOME, local IP can be found at Settings -> Network -> gear icon near your local connection -> IPv4 address. There is also a handy script for this task:
```
ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
```

So I have `192.168.1.36`, and I type `192.168.1.36:3000` for dev server and `192.168.1.36:5000/admin` for Admin UI.

**Comment by Ezra-Siton-UIX** [comment]
WOW :) Works great. If someone ever read this topic use [IPv4 ](https://forums.whatismyipaddress.com/viewtopic.php?t=3550)and no IP number.

 **Thanks a lot!** If this not causes any security problems I think like `google-starter-kit` It even worst to add this trick to the docs (Again this is useful).

**Comment by Ezra-Siton-UIX** [comment]
Last. On PC remember to turn this **on** (By default is OFF)
"Make this PC discoverable"
https://geekupwithyourdevices.blogspot.co.il/2017/06/how-to-configure-network-discovery-on.html
