### ISSUE TITLE
Folder to organize content in Admin Left Panel (UI)

### ISSUE THREAD

**Issue by Steven-lim1412** [Gottwik/Enduro#232]
Hello..

I understand that there is "generators" that allows user to create content based on predefined template. However I am not sure how I can create a simple folder to organize some content in Admin Left Panel (UI)?

Thanks

**Comment by Ezra-Siton-UIX** [comment]
No way. The folder in any CMS/builder is for hierarchy.
The left panel is organized like your pages structure.

I hope in the future enduro will give the ability to change the tree view order (The index should be first).

**"hierarchy"** The best way to show this is by screenshot :)
![image](https://user-images.githubusercontent.com/16711871/35644763-8e19fbe4-06d2-11e8-8eeb-053708584b41.png)

**Comment by Steven-lim1412** [comment]
Thanks Ezra 

Picture definitely speak a thousand words ;). While it does create a folder and to certain extend i understand the intention, i think it will be great if we can organize content (i.e. global) for better end user usability. For example, is the following.

-> settings
     -> site settings
     -> page settings
-> index
-> about us
-> blog

**Comment by Steven-lim1412** [comment]
Found the answer I am looking for. Simply create a folder under "global" and it will also reflect in the UI. Just need to make sure the reload happened.
