### ISSUE TITLE
Query String causes error

### ISSUE THREAD

**Issue by Steven-lim1412** [Gottwik/Enduro#236]
Query string causes "Error: ENOENT: no such file or directory" error, because it cant find the file in _generated folder. The error is only reproducible in production mode (localhost:5000) but not dev (localhost:3000), which makes sense as I believe in production mode the pages are served from _generated folder. 

Questions are:
1. How do I make the system not to look at _generated folder under production mode?
2. Otherwise, how do I get the _generated folder to ignore query string. (i.e. look at page 'C:\...\_generated\job-search?s=&loc=&cat=&subcat=\index.html).

Thanks

-Steven

**Comment by rnlambert7** [comment]
@tekwiz

**Comment by Steven-lim1412** [comment]
at the very least, will be great if there is a clue/direction on where I can have a look. Thanks.

**Comment by Steven-lim1412** [comment]
I have managed to resolve this by creating a new route in app.js

`// * ———————————————————————————————————————————————————————— * //
// * 	init
// *
// *	gets called upon starting enduro.js production server
// *	@param {express app} app - express app
// *	@return {nothing}
// * ———————————————————————————————————————————————————————— * //
local_app.prototype.init = function (app) {
	// express app available here
	// don't forget these routes will be available on production server server (defaults to localhost:5000)
    app.get('/job-search', function (req, res) {
        // serves the requested file
        res.sendFile(enduro.project_path + '/' + enduro.config.build_folder + '/job-search/index.html')
    })
}`
