### ISSUE TITLE
How to remove a administrator OR reset password of admin ? 

### ISSUE THREAD

**Issue by NLison** [Gottwik/Enduro#262]
How to remove a administrator OR reset password of admin ?

**Comment by Gottwik** [comment]
That's a good question. You can **remove** the user by editing `cms/.users` file (or just delete it alltogether).

I guess the best way to currently edit it is to delete it and create new user with `enduro admin add <username> <password>`.

Nice that you brought this up, I guess editing and removing users would be a nice easy feature to add.
