### ISSUE TITLE
nested elements get very small on admin panel

### ISSUE THREAD

**Issue by CordlessWool** [Gottwik/Enduro#263]
I nested some elements, to let admin chose between some elements. But this result in very small elements in admin panel (see picture). I saw you using bootstraps and remove md-col, the nested elements get bigger and everything is big enough. It only do not fit the hole wide.

I tried a little bit to get it with css, it will not be perfect. Here is one [example](https://jsfiddle.net/o605eere/14/).
Recognized, that the first element has no nest class.

![image](https://user-images.githubusercontent.com/17884035/39088740-b77ab932-45b7-11e8-8e9f-94de8d866659.png)

**Comment by Gottwik** [comment]
This is a good point. There is a `size` termination type that will set the size of child items in a bootstrapy columny way.

Use it like this:

```
```

**Comment by CordlessWool** [comment]
Do not work. It gives me a SintaxError: Invalid or enecpected token. It do not accept the  @

**Comment by anderalexdr** [comment]
Try replacing the '@' with a '$'. This way, it works for me.

**Comment by CordlessWool** [comment]
ok thank you, it work. I tried this also yesterday, but because of switching some time it had not work. 
Will it also be possible to set it on an templatitator type or global for all elements of the remplatitator?
