### ISSUE TITLE
Image loading error

### ISSUE THREAD

**Issue by oemueller** [Gottwik/Enduro#27]
Today I set up a test Enduro project and could not get uploaded images to work the way
I would expect. My uploaded images could not be loaded when browsing the build under localhost:3000

**Steps to reproduce:** 
- upload image "test.jpg". It is saved to folder remote/direct_uploads/
- Publish
- Load a test page referencing the uploaded image. Path still points to remote/direct_uploads/ - image can't be found. Testpage ist loaded from "frontend" with port 3000.

**Possible solution**
- is it possible to include images in the "static" build that goes to _src?

Regards,
Oliver

**Comment by Gottwik** [comment]
Hey @oemueller, I know exactly what you mean. I played with the local file system and somehow forgot about the _src folder.

Should be all fixed now, just update enduro by `npm i enduro -g` and let me know if it works ok for you.

**Comment by oemueller** [comment]
Now it works. Thank you 😀 👏
