### ISSUE TITLE
How extend bundler? And other questions

### ISSUE THREAD

**Issue by dimensi** [Gottwik/Enduro#276]
Hi, your project have nice idea. I can't found analogs. But i have tons of problems.
1. How extend bunlder? I want add some plugins for scss or do somework with others files.
2. How run enduro from js api, not from cli?
3. How controlling bundler in enduro?

**Comment by sylbal** [comment]
Extend bundler by adding custom tasks in gulp build process is an issue for us too. We're just starting using Enduro and we'll look at this point more deeply in the next days.
