### ISSUE TITLE
SEO // No way to add robots.txt file 

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/Enduro#288]
This file should be under the root `/` - but no way be enduro to add this file

https://developers.google.com/search/reference/robots_txt

**Comment by Ezra-Siton-UIX** [comment]
SAME IDEA/Problem FOR Sitemaps(but her I could tell google to look at "assets/sitemap.xml"

**Comment by eksoverzero** [comment]
@Ezra-Siton-UIX  Any file added to the `/assets/root/` directory will be copied to the website root when the site is generated.

**Comment by Ezra-Siton-UIX** [comment]
WOW, thanks. This idea should be added to the docs (No way to guess this!).

The main issue `sitemap.xml`

enduro sitemap.xml, enduro robots.txt
