### ISSUE TITLE
Publishing hook

### ISSUE THREAD

**Issue by oemueller** [Gottwik/Enduro#29]
I was wondering: is it possible to run a certain task when the _src build folder is updated ? 
This could be kind of a "build hook".  Or is there a event that could be listened for? 

After every build I have to copy the build folder to a different location so this needs to be a automatic task. 'gulp watch' might do the job, but that's less beautiful :-)

Thanks !

**Comment by Gottwik** [comment]
Thank you for the question @oemueller . Could you maybe explain a bit more why you need to copy the build folder?

**Comment by oemueller** [comment]
because I want to use the static build as part of another project that uses its own webserver. 
So it would be nice to get informed when a new build was made. 
I thought of installing Enduro locally and add such functionality but this would break on any updates.

**Comment by Gottwik** [comment]
That makes sense. I added event hooks, just update enduro to latest and this should work for you:

enduro.json:
```
{
	"project_name": "set name here",
	"project_slug": "sn",
	"s3": {
		"bucket": "enduro.sethere",
		"region": "eu-west-1"
	},
	"juicebox_enabled": false,
	"events": {
		"post_update": "cp -R _src/. ../eventcopy"
	}
}
```

Hey, let me know if this works for you.

**Comment by oemueller** [comment]
works like a charm 👍
thank you!
