### ISSUE TITLE
Suggestion: 'File' Field Type

### ISSUE THREAD

**Issue by davidbwaters** [Gottwik/Enduro#35]
Hi, it would be nice to have a file upload control type in the admin.  Thanks.

**Comment by Gottwik** [comment]
hey, what a great idea, I'll definitely get this done.

**Comment by Gottwik** [comment]
Donenitto. You can now upload files with a neat file control. Just use:

```
    {
        $best_file_ever_type: 'file',
        best_file_ever: '',
    }
```

![enduro_file_drop](https://user-images.githubusercontent.com/277311/27547320-e4ded844-5a95-11e7-9b21-4f8ade80a2e6.gif)

**Comment by CosmoMyzrailGorynych** [comment]
@Gottwik but it is absent in enduro-admin source files and doesn't work :c

**Comment by Gottwik** [comment]
Yea, my bad. It is there now. I had to fix some stuff for the test to pass on enduro_admin
