### ISSUE TITLE
Unable to setup Juicebox

### ISSUE THREAD

**Issue by eboebo** [Gottwik/Enduro#37]
Whenever I run

`enduro setup juicebox`

I get the following error:

`│ Arguments not recognized                                 │
(node:99069) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): not recognized`

It may also be worth mentioning that when I run 
`enduro --help` it starts the enduro in production mode...

I'm running node v6.9.0 and Enduro 1.4.3. 

I have tried uninstalling and installing different versions on Enduro. Sometimes the --help command will work but I have never been able to setup Juicebox.

**Comment by Gottwik** [comment]
Hey @eboebo , did you resolve this? Was it an old enduro version? Did running `npm i enduro -g` solve it?

**Comment by eboebo** [comment]
@Gottwik, yes `npm i enduro -g` solved the issue. 

However, I had previously deployed to heroku and my changes are not persisting. 

I make changes on the heroku site, run  `enduro juice pull` locally, and there are no updates. Am I missing something? Is the issue that I deployed before setting up juicebox?

**Comment by Gottwik** [comment]
Did you set up s3 yet? You need s3 because heroku has no persistent file storage. You can use `enduro setup s3`. If you do this, what you are doing will work as you are expecting it to work.

**Comment by eboebo** [comment]
I see, I set that up but now when I run enduro the app crashes after initiating juice pull

**Comment by eboebo** [comment]
@Gottwik Any clue why `enduro juice pull` would crash? I'm not getting any error logs, it just crashes. I set up the s3 bucket and all the information (name, region, credentials) looks right.

**Comment by Gottwik** [comment]
Help me out a little. Does it log out anything? There is logging in place for cases such as when the bucket does not exist and such.

What OS are you on? Could you try running `enduro juice diff` or `enduro juice log` to see if we get some information out of it?

**Comment by eboebo** [comment]
If I run  `enduro` it gets this far:


`┌——————Enduro started                 `
`│ Development server started at:                     │`
`│     localhost:3000                                            │`
`│ Admin ui available at:                                      │`
`│     localhost:5000/admin                                 │`
`│ Admin has no live-reload!                               │`

`[16:31:17 | +    2.39] developer start`
`┌———————Juice pull—~`

And then crashes. 

`enduro juice pull` initiates juice pull and crashes at the same place.

`enduro juice log` does nothing.

**Comment by eboebo** [comment]
@Gottwik I was able to figure out that my bucket permissions were not configured correctly and that enduro was not logging that information.

**Comment by Gottwik** [comment]
Good job on figuring out what was the problem, and thank you for discovering this. I added logging for bucket not being publicly accessible.

![image](https://cloud.githubusercontent.com/assets/277311/24835558/a45fe89e-1d05-11e7-9362-d035fe1b0429.png)

Good luck on your project and don't hesistate to open issues or improvement suggestions.
