### ISSUE TITLE
addadmin doesn't add to .users.js

### ISSUE THREAD

**Issue by ghettosoak** [Gottwik/Enduro#42]
`enduro addadmin testUser testPass` doesn't add to the .users.js file. I got it working by figuring out that you're using SHA256, and generating salts and hashes manually.

**Comment by Gottwik** [comment]
oh, yea, it has been changed to `enduro admin add testUser testPass`. Sorry about that, I also fixed it in documentation. Thank you for reporting this. Btw you can run `enduro --help` if you get a cli issue.

**Comment by ghettosoak** [comment]
ah, right on! thanks for the reply, and for updating the docs! excellent work btw, I got this integrated into a site in an afternoon! :D

**Comment by defong** [comment]
![image](https://cloud.githubusercontent.com/assets/470137/25133814/c31ad5d6-2445-11e7-9371-b9ad2ebfce65.png)

**Comment by Gottwik** [comment]
Oh, thank you, should be fixed. Do you have any other questions or issues?

**Comment by defong** [comment]
Here's another

![image](https://cloud.githubusercontent.com/assets/470137/25177347/6ba79d5c-24f9-11e7-9b8b-c69d56b9ed6e.png)

**Comment by Gottwik** [comment]
Nice catch, thank you

**Comment by ghettosoak** [comment]
ah, silly me. thanks! I think we can close this!

**Comment by Gottwik** [comment]
nah, my fault. Let me know if you have any other issues.
