### ISSUE TITLE
rename _src folder to _generated

### ISSUE THREAD

**Issue by Gottwik** [Gottwik/Enduro#44]
I don't know what I was thinking, _generated is much better and clearer name for the folder, right?

**Comment by CosmoMyzrailGorynych** [comment]
Maybe `dist`? Like "distribution". At least, it is common to make a dist folder in libraries

**Comment by oemueller** [comment]
other options are "build" and "deploy" or "static" ...

**Comment by CosmoMyzrailGorynych** [comment]
imho `static` is the best. It is self-descriptive and suits well both for static sites and hosted enduro apps.

На 19 апр. 2017 г., 23:56, в 23:56, Oliver <notifications@github.com> написал:п>other options are "build" and "deploy" or "static" ...

**Comment by ilyaigpetrov** [comment]
Here are names of output directories used by other static site generators:

Generator | Default output directory
---------------|-----------------------
Jekyll         | [_site](https://jekyllrb.com/docs/usage/)
hakyll        | [_site](https://jaspervdj.be/hakyll/tutorials/02-basics.html)
Hugo         | [public](https://gohugo.io/overview/usage/)
Hexo         | [public](https://hexo.io/docs/setup.html)
Metalsmith | [build](http://www.metalsmith.io)
Wintersmith | [build](https://github.com/jnordberg/wintersmith)

**Comment by justindra** [comment]
@Gottwik I'm happy to help out here, I was just looking at things, what do you think about adding a build path into a config, and setting the default to be `build`?
