### ISSUE TITLE
Any built-in way to just ship some files along with a pre-built site?

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#58]
Hey there,
Is there an easy (I mean built-in) way to just drop some files in a folder to be shipped with a static site?
E.g. I need to put favicons in a root folder of generated site.

**Comment by CosmoMyzrailGorynych** [comment]
Looks like putting files simply into /_src folder does the trick.
I wonder if this directory is cleaned sometimes?

**Comment by Gottwik** [comment]
putting files in `/_src` or newly `/_generated` is not a right way to do it since it's not part of the git repository and should contain only, well, generated files.

Do you need to put it in the root? Would putting the favicon in `/assets/img/favicon` work for you?

**Comment by CosmoMyzrailGorynych** [comment]
I do need putting some files to the root folder. Favico is just an example, but there is also `robots.txt` file that needs to be versioned and lay exactly in a generated root folder, it might also be CNAME record for Github pages, or verification files for different mail services

**Comment by Gottwik** [comment]
yea, this sounds like a good idea. I implemented it, just update enduro(`npm i enduro -g`) and put your files into `/assets/root` folder. Whichever you put here will get copied into the root of the _generated folder.

Let me know if this works for you :-)
