### ISSUE TITLE
npm install enduro -g errors

### ISSUE THREAD

**Issue by ministrycrm** [Gottwik/Enduro#59]
C17PN8T6G8WN:enduro xjxh209$ npm install enduro -g
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "enduro" "-g"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @gulp-sourcemaps/identity-map
npm ERR! 404 
npm ERR! 404  '@gulp-sourcemaps/identity-map' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Gottwik** [comment]
That's weird, right? Could you run `npm -v` and `node -v` for us?

**Comment by ministrycrm** [comment]
C17PN8T6G8WN:enduro xjxh209$ npm -v
3.10.10
C17PN8T6G8WN:enduro xjxh209$ node -v
v6.10.3

**Comment by h4v0c74** [comment]
Install does not complete, it just stops with zero errors. One odd result is that the cursor in my PuTTY window disappears, but I am still able to type and run commands. The output of "sudo npm install -g enduro":

$ sudo npm install -g enduro
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed          ...] \ extract:svgicons2svgfont: sill gunzTarPerm modified mode [ 'ts/rx.joinpatterns.d.ts', 384, 420 ]

Any thoughts or ideas?

Thanks :)

**Comment by h4v0c74** [comment]
Oops, forgot this:

$ node -v
v6.11.0

$ npm -v
3.10.10

**Comment by h4v0c74** [comment]
Nevermind, my issue turned out to me that my VPS ran out of memory.

**Comment by justindra** [comment]
Closing issue as its now fixed as above
