### ISSUE TITLE
missing dependency: gulp-less

### ISSUE THREAD

**Issue by oemueller** [Gottwik/Enduro#60]
right now "gulp-less": "^3.3.0" is a dev-dependency
My enduro instance is failing to run because gulp-less is not installed. 
I guess it should be a normal dependency right? 
(like gulp-sass)

What do you think?

**Comment by Gottwik** [comment]
Yea, the gulp-less was added by @justindra recently. You just need to run `npm i` in the enduro folder to fetch it again.

**Comment by CosmoMyzrailGorynych** [comment]
I installed gulp-less globally ('cause the enduro is installed in the same way), and now it requires `less-plugin-autoprefix`.

*installing...*

Whew, no more surprises after `npm install gulp-less --global` and `npm install less-plugin-autoprefix --global`

**Comment by oemueller** [comment]
@Gottwik ok, but I think both should be moved from dev-dependencies to dependencies, or do I miss something?

**Comment by Gottwik** [comment]
Oh, right, yes. Would you maybe want to create a pull request to fix it?

**Comment by Gottwik** [comment]
Fixed
