### ISSUE TITLE
Site is empty ['No such app' from Heroku]

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#61]
![image](https://cloud.githubusercontent.com/assets/3174357/26147478/cd133916-3b47-11e7-8589-6a6de4c5c61c.png)

**Comment by Gottwik** [comment]
yea, yea, I know. I'll figure it out. I recently relocated and don't have a credit card yet to pay for the hosting...

**Comment by peralov** [comment]
@Gottwik how much do you need for the hosting?

**Comment by Gottwik** [comment]
Got the credit card, everything is up now :-)
