### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/_generated/admin/index.html'

### ISSUE THREAD

**Issue by karneaud** [Gottwik/Enduro#72]
running endurojs in docker node:onbuild latest version of node and npm. After successfully executing `enduro create web && cd web && enduro` i get the following  output

> ————————————————————~—Enduro started—~————————————————————┐
> │ Development server started at:                           │
> │     localhost:3000                                       │
> │ Admin ui available at:                                   │
> │     localhost:5000/admin                                 │
> ├——————————————————————————————————————————————————————————┤
> │ Admin has no live-reload!                                │
> └——————————————————————————————————————————————————————————┘
> [03:33:45 | +    1.37] developer start
> [03:33:45 | +    0.09] Render started
> [03:33:45 | +    0.02] Sass compiling started
> [03:33:46 | +    0.14] Sass compiling finished
> [03:33:46 | +    0.02] Render finished
> [03:33:46 | +    0.01] browsersync started
> [03:33:46 | +    0.02] production server starting
> [03:33:46 | +    0.01] Production server started at port 5000
> 

going to localhost:3000 and localhost:5000 gives me

> Hey you!
> 
> Enduro is nice
> 
> Try it out yourself

which I assume is correct...however going to localhost:5000/admin gives me

> Error: ENOENT: no such file or directory, stat '/_generated/admin/index.html'

checking the directory structure I see there is no **admin** folder and **index.html** is in the *root* of **generated**

Am I missing a step here?

**Comment by Gottwik** [comment]
that's not good. I wasn't able to replicate this, although there has been changes with handling routing. Could you update enduro by running `npm i enduro -g` and check if it's still happening?

Or you can check `enduro --version` in the docker.

**Comment by karneaud** [comment]
@Gottwik that's funny as I was able to get it up and running using `endure theme mirror` not sure why the minimalistic version is doing this. 


Will try out suggestion

**Comment by Gottwik** [comment]
My guess would be to try to update enduro to the newest version and see if it wasn't fixed

**Comment by karneaud** [comment]
@Gottwik I'm installing endure via yarn.....should be the latest version correct?

**Comment by Gottwik** [comment]
can you check by running `enduro --version`? As of writing this, the most current is 1.4.24

**Comment by CosmoMyzrailGorynych** [comment]
Enduro shows such errors sometimes for other pages if there is no final slash in url. There seems to be some inconsistency. I can't find such routes now but will tell if i do.

**Comment by Gottwik** [comment]
hey, I'm going to close this ticket, feel free to re-open if you still have this issue

**Comment by alifgiant** [comment]
hi @Gottwik , after enduro create and enduro dev, I still get this error, I use enduro version 1.4.45
