### ISSUE TITLE
Custom Theme 

### ISSUE THREAD

**Issue by karneaud** [Gottwik/Enduro#73]
If I wanted to develop a theme that can be used via the command line how do I go about it?

**Comment by CosmoMyzrailGorynych** [comment]
It seems that you should make a 'template' enduro project like usual, and then submit a pull request to [themes list](https://github.com/Gottwik/enduro_website/blob/master/cms/global/theme_manager/themes.js) so people could clone it via command line.

https://www.endurojs.com/docs/themes#creating-enduro-js-themes

**Comment by Gottwik** [comment]
Hey, @CosmoMyzrailGorynych thank you for answering this one. I am going to close this ticket now.

@karneaud Please reach out should you have more questions.
