### ISSUE TITLE
Disable browsersync?

### ISSUE THREAD

**Issue by dijs** [Gottwik/Enduro#76]
Is this possible with some configuration?

**Comment by Gottwik** [comment]
Hey, thank you for the question. Could you maybe share a bit more why would you want to disable browsersync? You can always do `enduro start` which will start the webserver without any dev tools such as browsersync or watching for changes.

**Comment by dijs** [comment]
Great question.

I actually rather running the server in dev mode, since I can see immediate changes when I change files and change the admin.

But the browsersync is killing me, since all the users are seeing their screens scroll everywhere :/

**Comment by Gottwik** [comment]
hey, what do you mean all the users? Are there more people developing the website, or are these consumers?

**Comment by dijs** [comment]
consumers are seeing this. which kinda makes sense, since I am running in dev-mode.

**Comment by Gottwik** [comment]
em, can you point the consumers to port 5000? They will get the production version without reloading, scrolling and should be a bit faster as well.

**Comment by dijs** [comment]
You mean after running the server with `enduro start` right?

**Comment by Gottwik** [comment]
`enduro dev` will start both 3000 and 5000 servers(btw you can chance the ports).

So what's your setup? Do you develop on server? Why do consumers get to the port 3000?

**Comment by dijs** [comment]
Could I configure the production port to something different then 5000?

**Comment by dijs** [comment]
Ohh! It starts both servers... let me try on 5000 again...

**Comment by dijs** [comment]
Oh wow, MUCH faster. Thank you! for your very quick help!

**Comment by Gottwik** [comment]
sure, just do `enduro start -p=80`. For development mode you'll have to add `port: 80` in the enduro.json config file. On some servers port 80 is blocked by default so you'll have to start enduro with sudo.

**Comment by Gottwik** [comment]
hey, good luck on your project, let us know if you have any other issues :-)
