### ISSUE TITLE
Enduro documentation Not Found

### ISSUE THREAD

**Issue by masza** [Gottwik/Enduro#82]
Hello! Smth wrong happens with your documentation. All links, like this http://www.endurojs.com/docs/hello-world
show "Not found"

**Comment by Gottwik** [comment]
yup, broke it yesterday. Fixed today.

Awesome that you reported this 👍

**Comment by dave-irvine** [comment]
@Gottwik Also https://www.endurojs.com/docs/templates seems broken

**Comment by Gottwik** [comment]
I need to learn to wait until the change is live before commenting :-)

Everything should work fine now (checked it)

**Comment by dave-irvine** [comment]
@Gottwik Yeah looks good, thanks :)
