### ISSUE TITLE
 ENOENT: no such file or directory when use $enduro secure

### ISSUE THREAD

**Issue by masza** [Gottwik/Enduro#83]
When I try use "$enduro secure <pass>" and then open localhost:/5000 I get this error:

> Error: ENOENT: no such file or directory, stat '/.../node_modules/enduro_admin/_generated/enduro_login.html'

Thats probably because correct path is '/.../node_modules/enduro_admin/_generated/enduro_login/index.html'

;))

**Comment by Gottwik** [comment]
Awesome, thank you for the fix @masza
