### ISSUE TITLE
How to deploy on different server than heroku

### ISSUE THREAD

**Issue by masza** [Gottwik/Enduro#85]
Hello!
I'm new with this framework but I really like the concept of enduro.js Before I start develop sites based on enduro I want know is it even possible to deploy dynamic site on server which I use. My server use freeBSD OS, can handle with node.js but to run site there server start file MUST be app.js and all static filest MUST be in "public" folder. Is it any chance to run enduro.js site on this type of server?

**Comment by oemueller** [comment]
Yes, I think its just a matter of configuration.
What hoster are you using?

**Comment by masza** [comment]
I use mydevil.net This is local hoster from my country and they don't have english version of their site, so this isn't helpful for you.

**Comment by oemueller** [comment]
ok - so the first things to check are: 
- is required node + npm version installed
- what ports can be used for the backend / frontend of enduro (port 80 is normally restricted)

**Comment by masza** [comment]
@oemueller Now I use node version 4.8.2 and npm 4.0.5, but I can use newer version of node if I want, for example 6.9.4. 

Ports are added by Phusion Passenger. It choose and add first free port so I don't know which ports exacly can be used.

**Comment by oemueller** [comment]
Node 6.9.4 should work. Maybe your hoster can tell you which ports to use. 
Good luck!

**Comment by Gottwik** [comment]
@masza Did this get resolved for you? Feel free to reopen if not

**Comment by crevan236** [comment]
@masza I'm facing the same problem right now :/ Could you share your experience?

**Comment by masza** [comment]
I did't deployed it finally. I only tested this technology so I quickly
leaved it when I got problems with deploy.

pt., 6 lip 2018 o 20:13 Damian <notifications@github.com> napisał(a):

**Comment by crevan236** [comment]
Ok :(
Thanks for the feedbackh anyway =)

**Comment by Oldwo1f** [comment]
i think i ll do as Masza as i cant deploy the project on a non heroku server aswell
