### ISSUE TITLE
Mistake in document page: 'Deploy with static page'

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#86]
There is an error in this page:
http://www.endurojs.com/docs/static-pages

For ther is no '_src' folder, but a '_generated' folder.

And, after host the '_generated' folder, the blog-like content lost the css:
main.css Failed to load resource: the server responded with a status of 404 (Not Found)

for the relative path is not correct.

<img width="509" alt="screen shot 2017-07-13 at 2 43 09 pm" src="https://user-images.githubusercontent.com/6466550/28153854-40774ef6-67da-11e7-85eb-9ce4d172a487.png">

I guess that the path should be: '../assets/css/main.css'

**Comment by Gottwik** [comment]
Hey, thank you that you reported this. I replaced all `_src` with `_generated`. We just recently refactored the name and didn't fix the documentation.

Hey, try using `href="/assets/css/main.css"` instead(added forward slash to the beginning of the path)

**Comment by archcra** [comment]
I tried your suggestion, and it works!
Thank you very much!

**Comment by Gottwik** [comment]
Always happy to help :-) . Don't hesitate to reach out if you hit something.
