### ISSUE TITLE
Array in an array in admin control type

### ISSUE THREAD

**Issue by jowamedia** [Gottwik/Enduro#96]
In the mirror theme, index.js, I tried to add an array (galery) in the project array.
Goal -> add more images to the project.

Extraction of code index.js:
`	
projects: [
		{
			title: 'Autonomous submarine',
			$image_type: 'image',
			image: 'https://s3-eu-west-1.amazonaws.com/enduro.mirror/direct_uploads/1485880340_pexels-photo-27631.jpg',
			link: 'http://newatlas.com/boeing-echo-voyager/42272/'
			galery:  [
				{
					$images_proj_type: 'image',
					images_proj: 'https://s3-eu-west-1.amazonaws.com/enduro.mirror/direct_uploads/1485880340_pexels-photo-27631.jpg',
				}
			],
		},
`

But when I access the admin/index page, I got the following error :

`:15
                        galery:  [
                        ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at requireFromString (/home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/enduro/node_modules/require-from-string/index.js:27:4)
    at /home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/enduro/libs/flat_db/flat.js:89:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
malformed_context_file: index`

**Comment by CosmoMyzrailGorynych** [comment]
You've messed up with commas: there is no comma after `link` key, and you have three extra commas at the end of the code.

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CosmoMyzrailGorynych** [comment]
So it should be something like this:

```
projects: [ { 
  title: 'Autonomous submarine',
  $image_type: 'image', 
  image: 'https://s3-eu-west-1.amazonaws.com/enduro.mirror/direct_uploads/1485880340_pexels-photo-27631.jpg', 
  link: 'http://newatlas.com/boeing-echo-voyager/42272/',
  galery: [ { 
    $images_proj_type: 'image',
    images_proj: 'https://s3-eu-west-1.amazonaws.com/enduro.mirror/direct_uploads/1485880340_pexels-photo-27631.jpg'
  } ]
}

```


_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jowamedia** [comment]
Thanks a lot for your quick answer, and sorry for the my late feedback. Best regards.
