### ISSUE TITLE
Trollhunter feature not works

### ISSUE THREAD

**Issue by archcra** [Gottwik/Enduro#99]
After follow the document: http://www.endurojs.com/docs/trollhunter

I enabled security, and restart Enduro project, then visit:
http://localhost:5000/

I got such error:
Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/enduro/node_modules/enduro_admin/_generated/enduro_login.html'
    at Error (native)

both in the browser page and the command line terminal.

**Comment by Gottwik** [comment]
works fine for me. What endruo version are you using(`enduro --version`)?

**Comment by archcra** [comment]
$ enduro --version
1.4.31

P.S.
I appreciate Enduro very much, but,
I don't think such answers as 'works fine for me' is positive.

**Comment by Gottwik** [comment]
crap, sorry about that :-( Thank you for reporting this. I should have spent more time investigating this.

Fixed this in 9edbaee0e46aa514060095e3cda1ab0952edb97e, just update enduro(`npm i enduro -g`) and let me know if it works for you :-)

**Comment by archcra** [comment]
Works for me now, 
$ enduro --version
1.4.34

Thank you very much!
